on:
  push:
  schedule:
    - cron: '0 6,14,18 * * *'  # every day at midnight

jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: wget
        uses: enflo/curl-action@master
        with:
          curl: -o logs/counter.txt https://knihovna.pedf.cuni.cz/counter/counter.txt
      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'logs/counter.txt'
          author_name: "Commit bot"
          author_email: michal.hoftich@pedf.cuni.cz
      

